version: "3.8"
services:
  go-cars-db:
    container_name: go-cars-db
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks:
      - go-cars
    ports:
      - "5432:5432"

  go-cars:
    container_name: go-cars
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - go-cars
    depends_on:
      - go-cars-db
    ports:
      - "5000:5000"

networks:
  go-cars:
