definitions:
  controllers.addCarsDto:
    properties:
      regNums:
        items:
          type: string
        type: array
    required:
    - regNums
    type: object
  controllers.updateCarDto:
    properties:
      mark:
        type: string
      model:
        type: string
      regNum:
        type: string
      year:
        type: integer
    required:
    - regNum
    type: object
  models.Cars:
    properties:
      id:
        type: integer
      mark:
        type: string
      model:
        type: string
      owner:
        $ref: '#/definitions/models.Owners'
      ownerID:
        type: integer
      regNum:
        type: string
      year:
        type: integer
    type: object
  models.Owners:
    properties:
      id:
        type: integer
      name:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
info:
  contact: {}
paths:
  /add:
    post:
      consumes:
      - application/json
      description: Adds cars from source server by regNums
      parameters:
      - description: Cars' regNums
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/controllers.addCarsDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add cars
      tags:
      - cars
  /delete:
    delete:
      description: Deletes car selected by regNum
      parameters:
      - description: Car's regNum
        in: query
        name: regNum
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete car
      tags:
      - cars
  /get:
    get:
      description: Retrieve cars based on optional filters
      parameters:
      - description: Page number. Sets to 1 if not specified
        in: query
        name: page
        type: integer
      - description: Amount of cars per page. Sets to 10 if not specified
        in: query
        name: amount
        type: integer
      - description: Optional car's regNum filter
        in: query
        name: regNum
        type: string
      - description: Optional car's mark filter
        in: query
        name: mark
        type: string
      - description: Optional car's year filter
        in: query
        name: year
        type: integer
      - description: Optional owner's name filter
        in: query
        name: name
        type: string
      - description: Optional owner's surname filter
        in: query
        name: surname
        type: string
      - description: Optional owner's patronymic filter
        in: query
        name: patronymic
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Cars'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get cars
      tags:
      - cars
  /update:
    patch:
      consumes:
      - application/json
      description: Updates provided fields of car selected by regNum
      parameters:
      - description: Updated information
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/controllers.updateCarDto'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update car
      tags:
      - cars
swagger: "2.0"
